server:
    port: ${PORT:5500}
    error:
        whitelabel:
            enabled: false
        path: /errors

spring:
    datasource:
        url: jdbc:h2:mem:test
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
        platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true
            path: /console/db
            settings:
                trace: true
                web-allow-others: true